// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CreateEdgeConfigTokenRequestBody struct {
	Label string `json:"label"`
}

func (o *CreateEdgeConfigTokenRequestBody) GetLabel() string {
	if o == nil {
		return ""
	}
	return o.Label
}

type CreateEdgeConfigTokenRequest struct {
	RequestBody  *CreateEdgeConfigTokenRequestBody `request:"mediaType=application/json"`
	EdgeConfigID string                            `pathParam:"style=simple,explode=false,name=edgeConfigId"`
	// The Team slug to perform the request on behalf of.
	Slug *string `queryParam:"style=form,explode=true,name=slug"`
	// The Team identifier to perform the request on behalf of.
	TeamID *string `queryParam:"style=form,explode=true,name=teamId"`
}

func (o *CreateEdgeConfigTokenRequest) GetRequestBody() *CreateEdgeConfigTokenRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *CreateEdgeConfigTokenRequest) GetEdgeConfigID() string {
	if o == nil {
		return ""
	}
	return o.EdgeConfigID
}

func (o *CreateEdgeConfigTokenRequest) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

func (o *CreateEdgeConfigTokenRequest) GetTeamID() *string {
	if o == nil {
		return nil
	}
	return o.TeamID
}

type CreateEdgeConfigTokenResponseBody struct {
	ID    string `json:"id"`
	Token string `json:"token"`
}

func (o *CreateEdgeConfigTokenResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateEdgeConfigTokenResponseBody) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}

type CreateEdgeConfigTokenResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	Object      *CreateEdgeConfigTokenResponseBody
}

func (o *CreateEdgeConfigTokenResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateEdgeConfigTokenResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateEdgeConfigTokenResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateEdgeConfigTokenResponse) GetObject() *CreateEdgeConfigTokenResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
