// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/vercel/terraform-provider-terraform/internal/sdk/internal/utils"
	"net/http"
)

type GetConfigurationRequest struct {
	// ID of the configuration to check
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// The Team identifier to perform the request on behalf of.
	TeamID *string `queryParam:"style=form,explode=true,name=teamId"`
	// The Team slug to perform the request on behalf of.
	Slug *string `queryParam:"style=form,explode=true,name=slug"`
}

func (o *GetConfigurationRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetConfigurationRequest) GetTeamID() *string {
	if o == nil {
		return nil
	}
	return o.TeamID
}

func (o *GetConfigurationRequest) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

// ProjectSelection - A string representing the permission for projects. Possible values are `all` or `selected`.
type ProjectSelection string

const (
	ProjectSelectionSelected ProjectSelection = "selected"
	ProjectSelectionAll      ProjectSelection = "all"
)

func (e ProjectSelection) ToPointer() *ProjectSelection {
	return &e
}
func (e *ProjectSelection) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "selected":
		fallthrough
	case "all":
		*e = ProjectSelection(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ProjectSelection: %v", v)
	}
}

// GetConfigurationResponseBodyIntegrationsSource - Source defines where the configuration was installed from. It is used to analyze user engagement for integration installations in product metrics.
type GetConfigurationResponseBodyIntegrationsSource string

const (
	GetConfigurationResponseBodyIntegrationsSourceMarketplace  GetConfigurationResponseBodyIntegrationsSource = "marketplace"
	GetConfigurationResponseBodyIntegrationsSourceDeployButton GetConfigurationResponseBodyIntegrationsSource = "deploy-button"
	GetConfigurationResponseBodyIntegrationsSourceExternal     GetConfigurationResponseBodyIntegrationsSource = "external"
)

func (e GetConfigurationResponseBodyIntegrationsSource) ToPointer() *GetConfigurationResponseBodyIntegrationsSource {
	return &e
}
func (e *GetConfigurationResponseBodyIntegrationsSource) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "marketplace":
		fallthrough
	case "deploy-button":
		fallthrough
	case "external":
		*e = GetConfigurationResponseBodyIntegrationsSource(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetConfigurationResponseBodyIntegrationsSource: %v", v)
	}
}

type GetConfigurationResponseBodyIntegrationsType string

const (
	GetConfigurationResponseBodyIntegrationsTypeIntegrationConfiguration GetConfigurationResponseBodyIntegrationsType = "integration-configuration"
)

func (e GetConfigurationResponseBodyIntegrationsType) ToPointer() *GetConfigurationResponseBodyIntegrationsType {
	return &e
}
func (e *GetConfigurationResponseBodyIntegrationsType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "integration-configuration":
		*e = GetConfigurationResponseBodyIntegrationsType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetConfigurationResponseBodyIntegrationsType: %v", v)
	}
}

type GetConfigurationResponseBodyIntegrationsAdded string

const (
	GetConfigurationResponseBodyIntegrationsAddedReadIntegrationConfiguration      GetConfigurationResponseBodyIntegrationsAdded = "read:integration-configuration"
	GetConfigurationResponseBodyIntegrationsAddedReadWriteIntegrationConfiguration GetConfigurationResponseBodyIntegrationsAdded = "read-write:integration-configuration"
	GetConfigurationResponseBodyIntegrationsAddedReadDeployment                    GetConfigurationResponseBodyIntegrationsAdded = "read:deployment"
	GetConfigurationResponseBodyIntegrationsAddedReadWriteDeployment               GetConfigurationResponseBodyIntegrationsAdded = "read-write:deployment"
	GetConfigurationResponseBodyIntegrationsAddedReadWriteDeploymentCheck          GetConfigurationResponseBodyIntegrationsAdded = "read-write:deployment-check"
	GetConfigurationResponseBodyIntegrationsAddedReadProject                       GetConfigurationResponseBodyIntegrationsAdded = "read:project"
	GetConfigurationResponseBodyIntegrationsAddedReadWriteProject                  GetConfigurationResponseBodyIntegrationsAdded = "read-write:project"
	GetConfigurationResponseBodyIntegrationsAddedReadWriteProjectEnvVars           GetConfigurationResponseBodyIntegrationsAdded = "read-write:project-env-vars"
	GetConfigurationResponseBodyIntegrationsAddedReadWriteGlobalProjectEnvVars     GetConfigurationResponseBodyIntegrationsAdded = "read-write:global-project-env-vars"
	GetConfigurationResponseBodyIntegrationsAddedReadTeam                          GetConfigurationResponseBodyIntegrationsAdded = "read:team"
	GetConfigurationResponseBodyIntegrationsAddedReadUser                          GetConfigurationResponseBodyIntegrationsAdded = "read:user"
	GetConfigurationResponseBodyIntegrationsAddedReadWriteLogDrain                 GetConfigurationResponseBodyIntegrationsAdded = "read-write:log-drain"
	GetConfigurationResponseBodyIntegrationsAddedReadDomain                        GetConfigurationResponseBodyIntegrationsAdded = "read:domain"
	GetConfigurationResponseBodyIntegrationsAddedReadWriteDomain                   GetConfigurationResponseBodyIntegrationsAdded = "read-write:domain"
	GetConfigurationResponseBodyIntegrationsAddedReadWriteEdgeConfig               GetConfigurationResponseBodyIntegrationsAdded = "read-write:edge-config"
	GetConfigurationResponseBodyIntegrationsAddedReadWriteOtelEndpoint             GetConfigurationResponseBodyIntegrationsAdded = "read-write:otel-endpoint"
	GetConfigurationResponseBodyIntegrationsAddedReadMonitoring                    GetConfigurationResponseBodyIntegrationsAdded = "read:monitoring"
	GetConfigurationResponseBodyIntegrationsAddedReadWriteIntegrationResource      GetConfigurationResponseBodyIntegrationsAdded = "read-write:integration-resource"
)

func (e GetConfigurationResponseBodyIntegrationsAdded) ToPointer() *GetConfigurationResponseBodyIntegrationsAdded {
	return &e
}
func (e *GetConfigurationResponseBodyIntegrationsAdded) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "read:integration-configuration":
		fallthrough
	case "read-write:integration-configuration":
		fallthrough
	case "read:deployment":
		fallthrough
	case "read-write:deployment":
		fallthrough
	case "read-write:deployment-check":
		fallthrough
	case "read:project":
		fallthrough
	case "read-write:project":
		fallthrough
	case "read-write:project-env-vars":
		fallthrough
	case "read-write:global-project-env-vars":
		fallthrough
	case "read:team":
		fallthrough
	case "read:user":
		fallthrough
	case "read-write:log-drain":
		fallthrough
	case "read:domain":
		fallthrough
	case "read-write:domain":
		fallthrough
	case "read-write:edge-config":
		fallthrough
	case "read-write:otel-endpoint":
		fallthrough
	case "read:monitoring":
		fallthrough
	case "read-write:integration-resource":
		*e = GetConfigurationResponseBodyIntegrationsAdded(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetConfigurationResponseBodyIntegrationsAdded: %v", v)
	}
}

type GetConfigurationResponseBodyIntegrationsUpgraded string

const (
	GetConfigurationResponseBodyIntegrationsUpgradedReadIntegrationConfiguration      GetConfigurationResponseBodyIntegrationsUpgraded = "read:integration-configuration"
	GetConfigurationResponseBodyIntegrationsUpgradedReadWriteIntegrationConfiguration GetConfigurationResponseBodyIntegrationsUpgraded = "read-write:integration-configuration"
	GetConfigurationResponseBodyIntegrationsUpgradedReadDeployment                    GetConfigurationResponseBodyIntegrationsUpgraded = "read:deployment"
	GetConfigurationResponseBodyIntegrationsUpgradedReadWriteDeployment               GetConfigurationResponseBodyIntegrationsUpgraded = "read-write:deployment"
	GetConfigurationResponseBodyIntegrationsUpgradedReadWriteDeploymentCheck          GetConfigurationResponseBodyIntegrationsUpgraded = "read-write:deployment-check"
	GetConfigurationResponseBodyIntegrationsUpgradedReadProject                       GetConfigurationResponseBodyIntegrationsUpgraded = "read:project"
	GetConfigurationResponseBodyIntegrationsUpgradedReadWriteProject                  GetConfigurationResponseBodyIntegrationsUpgraded = "read-write:project"
	GetConfigurationResponseBodyIntegrationsUpgradedReadWriteProjectEnvVars           GetConfigurationResponseBodyIntegrationsUpgraded = "read-write:project-env-vars"
	GetConfigurationResponseBodyIntegrationsUpgradedReadWriteGlobalProjectEnvVars     GetConfigurationResponseBodyIntegrationsUpgraded = "read-write:global-project-env-vars"
	GetConfigurationResponseBodyIntegrationsUpgradedReadTeam                          GetConfigurationResponseBodyIntegrationsUpgraded = "read:team"
	GetConfigurationResponseBodyIntegrationsUpgradedReadUser                          GetConfigurationResponseBodyIntegrationsUpgraded = "read:user"
	GetConfigurationResponseBodyIntegrationsUpgradedReadWriteLogDrain                 GetConfigurationResponseBodyIntegrationsUpgraded = "read-write:log-drain"
	GetConfigurationResponseBodyIntegrationsUpgradedReadDomain                        GetConfigurationResponseBodyIntegrationsUpgraded = "read:domain"
	GetConfigurationResponseBodyIntegrationsUpgradedReadWriteDomain                   GetConfigurationResponseBodyIntegrationsUpgraded = "read-write:domain"
	GetConfigurationResponseBodyIntegrationsUpgradedReadWriteEdgeConfig               GetConfigurationResponseBodyIntegrationsUpgraded = "read-write:edge-config"
	GetConfigurationResponseBodyIntegrationsUpgradedReadWriteOtelEndpoint             GetConfigurationResponseBodyIntegrationsUpgraded = "read-write:otel-endpoint"
	GetConfigurationResponseBodyIntegrationsUpgradedReadMonitoring                    GetConfigurationResponseBodyIntegrationsUpgraded = "read:monitoring"
	GetConfigurationResponseBodyIntegrationsUpgradedReadWriteIntegrationResource      GetConfigurationResponseBodyIntegrationsUpgraded = "read-write:integration-resource"
)

func (e GetConfigurationResponseBodyIntegrationsUpgraded) ToPointer() *GetConfigurationResponseBodyIntegrationsUpgraded {
	return &e
}
func (e *GetConfigurationResponseBodyIntegrationsUpgraded) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "read:integration-configuration":
		fallthrough
	case "read-write:integration-configuration":
		fallthrough
	case "read:deployment":
		fallthrough
	case "read-write:deployment":
		fallthrough
	case "read-write:deployment-check":
		fallthrough
	case "read:project":
		fallthrough
	case "read-write:project":
		fallthrough
	case "read-write:project-env-vars":
		fallthrough
	case "read-write:global-project-env-vars":
		fallthrough
	case "read:team":
		fallthrough
	case "read:user":
		fallthrough
	case "read-write:log-drain":
		fallthrough
	case "read:domain":
		fallthrough
	case "read-write:domain":
		fallthrough
	case "read-write:edge-config":
		fallthrough
	case "read-write:otel-endpoint":
		fallthrough
	case "read:monitoring":
		fallthrough
	case "read-write:integration-resource":
		*e = GetConfigurationResponseBodyIntegrationsUpgraded(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetConfigurationResponseBodyIntegrationsUpgraded: %v", v)
	}
}

type GetConfigurationResponseBodyIntegrationsScopes struct {
	Added    []GetConfigurationResponseBodyIntegrationsAdded    `json:"added"`
	Upgraded []GetConfigurationResponseBodyIntegrationsUpgraded `json:"upgraded"`
}

func (o *GetConfigurationResponseBodyIntegrationsScopes) GetAdded() []GetConfigurationResponseBodyIntegrationsAdded {
	if o == nil {
		return []GetConfigurationResponseBodyIntegrationsAdded{}
	}
	return o.Added
}

func (o *GetConfigurationResponseBodyIntegrationsScopes) GetUpgraded() []GetConfigurationResponseBodyIntegrationsUpgraded {
	if o == nil {
		return []GetConfigurationResponseBodyIntegrationsUpgraded{}
	}
	return o.Upgraded
}

type GetConfigurationResponseBodyIntegrationsScopesQueue struct {
	Scopes      GetConfigurationResponseBodyIntegrationsScopes `json:"scopes"`
	Note        string                                         `json:"note"`
	RequestedAt float64                                        `json:"requestedAt"`
	ConfirmedAt *float64                                       `json:"confirmedAt,omitempty"`
}

func (o *GetConfigurationResponseBodyIntegrationsScopesQueue) GetScopes() GetConfigurationResponseBodyIntegrationsScopes {
	if o == nil {
		return GetConfigurationResponseBodyIntegrationsScopes{}
	}
	return o.Scopes
}

func (o *GetConfigurationResponseBodyIntegrationsScopesQueue) GetNote() string {
	if o == nil {
		return ""
	}
	return o.Note
}

func (o *GetConfigurationResponseBodyIntegrationsScopesQueue) GetRequestedAt() float64 {
	if o == nil {
		return 0.0
	}
	return o.RequestedAt
}

func (o *GetConfigurationResponseBodyIntegrationsScopesQueue) GetConfirmedAt() *float64 {
	if o == nil {
		return nil
	}
	return o.ConfirmedAt
}

type GetConfigurationResponseBodyIntegrationsDisabledReason string

const (
	GetConfigurationResponseBodyIntegrationsDisabledReasonDisabledByOwner          GetConfigurationResponseBodyIntegrationsDisabledReason = "disabled-by-owner"
	GetConfigurationResponseBodyIntegrationsDisabledReasonFeatureNotAvailable      GetConfigurationResponseBodyIntegrationsDisabledReason = "feature-not-available"
	GetConfigurationResponseBodyIntegrationsDisabledReasonDisabledByAdmin          GetConfigurationResponseBodyIntegrationsDisabledReason = "disabled-by-admin"
	GetConfigurationResponseBodyIntegrationsDisabledReasonOriginalOwnerLeftTheTeam GetConfigurationResponseBodyIntegrationsDisabledReason = "original-owner-left-the-team"
)

func (e GetConfigurationResponseBodyIntegrationsDisabledReason) ToPointer() *GetConfigurationResponseBodyIntegrationsDisabledReason {
	return &e
}
func (e *GetConfigurationResponseBodyIntegrationsDisabledReason) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "disabled-by-owner":
		fallthrough
	case "feature-not-available":
		fallthrough
	case "disabled-by-admin":
		fallthrough
	case "original-owner-left-the-team":
		*e = GetConfigurationResponseBodyIntegrationsDisabledReason(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetConfigurationResponseBodyIntegrationsDisabledReason: %v", v)
	}
}

// GetConfigurationResponseBodyIntegrationsInstallationType - Defines the installation type. - 'external' integrations are installed via the existing integrations flow - 'marketplace' integrations are natively installed: - when accepting the TOS of a partner during the store creation process - if undefined, assume 'external'
type GetConfigurationResponseBodyIntegrationsInstallationType string

const (
	GetConfigurationResponseBodyIntegrationsInstallationTypeMarketplace GetConfigurationResponseBodyIntegrationsInstallationType = "marketplace"
	GetConfigurationResponseBodyIntegrationsInstallationTypeExternal    GetConfigurationResponseBodyIntegrationsInstallationType = "external"
)

func (e GetConfigurationResponseBodyIntegrationsInstallationType) ToPointer() *GetConfigurationResponseBodyIntegrationsInstallationType {
	return &e
}
func (e *GetConfigurationResponseBodyIntegrationsInstallationType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "marketplace":
		fallthrough
	case "external":
		*e = GetConfigurationResponseBodyIntegrationsInstallationType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetConfigurationResponseBodyIntegrationsInstallationType: %v", v)
	}
}

type GetConfigurationResponseBody2 struct {
	// A string representing the permission for projects. Possible values are `all` or `selected`.
	ProjectSelection ProjectSelection `json:"projectSelection"`
	// When a configuration is limited to access certain projects, this will contain each of the project ID it is allowed to access. If it is not defined, the configuration has full access.
	Projects []string `json:"projects,omitempty"`
	// A timestamp that tells you when the configuration was installed successfully
	CompletedAt *float64 `json:"completedAt,omitempty"`
	// A timestamp that tells you when the configuration was created
	CreatedAt float64 `json:"createdAt"`
	// The unique identifier of the configuration
	ID string `json:"id"`
	// The unique identifier of the app the configuration was created for
	IntegrationID string `json:"integrationId"`
	// The user or team ID that owns the configuration
	OwnerID string `json:"ownerId"`
	// Source defines where the configuration was installed from. It is used to analyze user engagement for integration installations in product metrics.
	Source               *GetConfigurationResponseBodyIntegrationsSource `json:"source,omitempty"`
	RemovedLogDrainsAt   *float64                                        `json:"removedLogDrainsAt,omitempty"`
	RemovedProjectEnvsAt *float64                                        `json:"removedProjectEnvsAt,omitempty"`
	RemovedTokensAt      *float64                                        `json:"removedTokensAt,omitempty"`
	RemovedWebhooksAt    *float64                                        `json:"removedWebhooksAt,omitempty"`
	// The slug of the integration the configuration is created for.
	Slug string `json:"slug"`
	// When the configuration was created for a team, this will show the ID of the team.
	TeamID *string                                      `json:"teamId,omitempty"`
	Type   GetConfigurationResponseBodyIntegrationsType `json:"type"`
	// A timestamp that tells you when the configuration was updated.
	UpdatedAt float64 `json:"updatedAt"`
	// The ID of the user that created the configuration.
	UserID string `json:"userId"`
	// The resources that are allowed to be accessed by the configuration.
	Scopes      []string                                              `json:"scopes"`
	ScopesQueue []GetConfigurationResponseBodyIntegrationsScopesQueue `json:"scopesQueue,omitempty"`
	// A timestamp that tells you when the configuration was disabled. Note: Configurations can be disabled when the associated user loses access to a team. They do not function during this time until the configuration is 'transferred', meaning the associated user is changed to one with access to the team.
	DisabledAt *float64 `json:"disabledAt,omitempty"`
	// A timestamp that tells you when the configuration was updated.
	DeletedAt      *float64                                                `json:"deletedAt,omitempty"`
	DisabledReason *GetConfigurationResponseBodyIntegrationsDisabledReason `json:"disabledReason,omitempty"`
	// A timestamp that tells you when the configuration was migrated as part of the Northstar migration. In the future, if we allow integration configurations to be transferred between teams, this field should be cleared upon transfer.
	NorthstarMigratedAt *float64 `json:"northstarMigratedAt,omitempty"`
	// Defines the installation type. - 'external' integrations are installed via the existing integrations flow - 'marketplace' integrations are natively installed: - when accepting the TOS of a partner during the store creation process - if undefined, assume 'external'
	InstallationType          *GetConfigurationResponseBodyIntegrationsInstallationType `json:"installationType,omitempty"`
	CanConfigureOpenTelemetry *bool                                                     `json:"canConfigureOpenTelemetry,omitempty"`
}

func (o *GetConfigurationResponseBody2) GetProjectSelection() ProjectSelection {
	if o == nil {
		return ProjectSelection("")
	}
	return o.ProjectSelection
}

func (o *GetConfigurationResponseBody2) GetProjects() []string {
	if o == nil {
		return nil
	}
	return o.Projects
}

func (o *GetConfigurationResponseBody2) GetCompletedAt() *float64 {
	if o == nil {
		return nil
	}
	return o.CompletedAt
}

func (o *GetConfigurationResponseBody2) GetCreatedAt() float64 {
	if o == nil {
		return 0.0
	}
	return o.CreatedAt
}

func (o *GetConfigurationResponseBody2) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetConfigurationResponseBody2) GetIntegrationID() string {
	if o == nil {
		return ""
	}
	return o.IntegrationID
}

func (o *GetConfigurationResponseBody2) GetOwnerID() string {
	if o == nil {
		return ""
	}
	return o.OwnerID
}

func (o *GetConfigurationResponseBody2) GetSource() *GetConfigurationResponseBodyIntegrationsSource {
	if o == nil {
		return nil
	}
	return o.Source
}

func (o *GetConfigurationResponseBody2) GetRemovedLogDrainsAt() *float64 {
	if o == nil {
		return nil
	}
	return o.RemovedLogDrainsAt
}

func (o *GetConfigurationResponseBody2) GetRemovedProjectEnvsAt() *float64 {
	if o == nil {
		return nil
	}
	return o.RemovedProjectEnvsAt
}

func (o *GetConfigurationResponseBody2) GetRemovedTokensAt() *float64 {
	if o == nil {
		return nil
	}
	return o.RemovedTokensAt
}

func (o *GetConfigurationResponseBody2) GetRemovedWebhooksAt() *float64 {
	if o == nil {
		return nil
	}
	return o.RemovedWebhooksAt
}

func (o *GetConfigurationResponseBody2) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *GetConfigurationResponseBody2) GetTeamID() *string {
	if o == nil {
		return nil
	}
	return o.TeamID
}

func (o *GetConfigurationResponseBody2) GetType() GetConfigurationResponseBodyIntegrationsType {
	if o == nil {
		return GetConfigurationResponseBodyIntegrationsType("")
	}
	return o.Type
}

func (o *GetConfigurationResponseBody2) GetUpdatedAt() float64 {
	if o == nil {
		return 0.0
	}
	return o.UpdatedAt
}

func (o *GetConfigurationResponseBody2) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}

func (o *GetConfigurationResponseBody2) GetScopes() []string {
	if o == nil {
		return []string{}
	}
	return o.Scopes
}

func (o *GetConfigurationResponseBody2) GetScopesQueue() []GetConfigurationResponseBodyIntegrationsScopesQueue {
	if o == nil {
		return nil
	}
	return o.ScopesQueue
}

func (o *GetConfigurationResponseBody2) GetDisabledAt() *float64 {
	if o == nil {
		return nil
	}
	return o.DisabledAt
}

func (o *GetConfigurationResponseBody2) GetDeletedAt() *float64 {
	if o == nil {
		return nil
	}
	return o.DeletedAt
}

func (o *GetConfigurationResponseBody2) GetDisabledReason() *GetConfigurationResponseBodyIntegrationsDisabledReason {
	if o == nil {
		return nil
	}
	return o.DisabledReason
}

func (o *GetConfigurationResponseBody2) GetNorthstarMigratedAt() *float64 {
	if o == nil {
		return nil
	}
	return o.NorthstarMigratedAt
}

func (o *GetConfigurationResponseBody2) GetInstallationType() *GetConfigurationResponseBodyIntegrationsInstallationType {
	if o == nil {
		return nil
	}
	return o.InstallationType
}

func (o *GetConfigurationResponseBody2) GetCanConfigureOpenTelemetry() *bool {
	if o == nil {
		return nil
	}
	return o.CanConfigureOpenTelemetry
}

// GetConfigurationResponseBodySource - Source defines where the configuration was installed from. It is used to analyze user engagement for integration installations in product metrics.
type GetConfigurationResponseBodySource string

const (
	GetConfigurationResponseBodySourceMarketplace  GetConfigurationResponseBodySource = "marketplace"
	GetConfigurationResponseBodySourceDeployButton GetConfigurationResponseBodySource = "deploy-button"
	GetConfigurationResponseBodySourceExternal     GetConfigurationResponseBodySource = "external"
)

func (e GetConfigurationResponseBodySource) ToPointer() *GetConfigurationResponseBodySource {
	return &e
}
func (e *GetConfigurationResponseBodySource) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "marketplace":
		fallthrough
	case "deploy-button":
		fallthrough
	case "external":
		*e = GetConfigurationResponseBodySource(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetConfigurationResponseBodySource: %v", v)
	}
}

type GetConfigurationResponseBodyType string

const (
	GetConfigurationResponseBodyTypeIntegrationConfiguration GetConfigurationResponseBodyType = "integration-configuration"
)

func (e GetConfigurationResponseBodyType) ToPointer() *GetConfigurationResponseBodyType {
	return &e
}
func (e *GetConfigurationResponseBodyType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "integration-configuration":
		*e = GetConfigurationResponseBodyType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetConfigurationResponseBodyType: %v", v)
	}
}

type GetConfigurationResponseBodyAdded string

const (
	GetConfigurationResponseBodyAddedReadIntegrationConfiguration      GetConfigurationResponseBodyAdded = "read:integration-configuration"
	GetConfigurationResponseBodyAddedReadWriteIntegrationConfiguration GetConfigurationResponseBodyAdded = "read-write:integration-configuration"
	GetConfigurationResponseBodyAddedReadDeployment                    GetConfigurationResponseBodyAdded = "read:deployment"
	GetConfigurationResponseBodyAddedReadWriteDeployment               GetConfigurationResponseBodyAdded = "read-write:deployment"
	GetConfigurationResponseBodyAddedReadWriteDeploymentCheck          GetConfigurationResponseBodyAdded = "read-write:deployment-check"
	GetConfigurationResponseBodyAddedReadProject                       GetConfigurationResponseBodyAdded = "read:project"
	GetConfigurationResponseBodyAddedReadWriteProject                  GetConfigurationResponseBodyAdded = "read-write:project"
	GetConfigurationResponseBodyAddedReadWriteProjectEnvVars           GetConfigurationResponseBodyAdded = "read-write:project-env-vars"
	GetConfigurationResponseBodyAddedReadWriteGlobalProjectEnvVars     GetConfigurationResponseBodyAdded = "read-write:global-project-env-vars"
	GetConfigurationResponseBodyAddedReadTeam                          GetConfigurationResponseBodyAdded = "read:team"
	GetConfigurationResponseBodyAddedReadUser                          GetConfigurationResponseBodyAdded = "read:user"
	GetConfigurationResponseBodyAddedReadWriteLogDrain                 GetConfigurationResponseBodyAdded = "read-write:log-drain"
	GetConfigurationResponseBodyAddedReadDomain                        GetConfigurationResponseBodyAdded = "read:domain"
	GetConfigurationResponseBodyAddedReadWriteDomain                   GetConfigurationResponseBodyAdded = "read-write:domain"
	GetConfigurationResponseBodyAddedReadWriteEdgeConfig               GetConfigurationResponseBodyAdded = "read-write:edge-config"
	GetConfigurationResponseBodyAddedReadWriteOtelEndpoint             GetConfigurationResponseBodyAdded = "read-write:otel-endpoint"
	GetConfigurationResponseBodyAddedReadMonitoring                    GetConfigurationResponseBodyAdded = "read:monitoring"
	GetConfigurationResponseBodyAddedReadWriteIntegrationResource      GetConfigurationResponseBodyAdded = "read-write:integration-resource"
)

func (e GetConfigurationResponseBodyAdded) ToPointer() *GetConfigurationResponseBodyAdded {
	return &e
}
func (e *GetConfigurationResponseBodyAdded) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "read:integration-configuration":
		fallthrough
	case "read-write:integration-configuration":
		fallthrough
	case "read:deployment":
		fallthrough
	case "read-write:deployment":
		fallthrough
	case "read-write:deployment-check":
		fallthrough
	case "read:project":
		fallthrough
	case "read-write:project":
		fallthrough
	case "read-write:project-env-vars":
		fallthrough
	case "read-write:global-project-env-vars":
		fallthrough
	case "read:team":
		fallthrough
	case "read:user":
		fallthrough
	case "read-write:log-drain":
		fallthrough
	case "read:domain":
		fallthrough
	case "read-write:domain":
		fallthrough
	case "read-write:edge-config":
		fallthrough
	case "read-write:otel-endpoint":
		fallthrough
	case "read:monitoring":
		fallthrough
	case "read-write:integration-resource":
		*e = GetConfigurationResponseBodyAdded(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetConfigurationResponseBodyAdded: %v", v)
	}
}

type GetConfigurationResponseBodyUpgraded string

const (
	GetConfigurationResponseBodyUpgradedReadIntegrationConfiguration      GetConfigurationResponseBodyUpgraded = "read:integration-configuration"
	GetConfigurationResponseBodyUpgradedReadWriteIntegrationConfiguration GetConfigurationResponseBodyUpgraded = "read-write:integration-configuration"
	GetConfigurationResponseBodyUpgradedReadDeployment                    GetConfigurationResponseBodyUpgraded = "read:deployment"
	GetConfigurationResponseBodyUpgradedReadWriteDeployment               GetConfigurationResponseBodyUpgraded = "read-write:deployment"
	GetConfigurationResponseBodyUpgradedReadWriteDeploymentCheck          GetConfigurationResponseBodyUpgraded = "read-write:deployment-check"
	GetConfigurationResponseBodyUpgradedReadProject                       GetConfigurationResponseBodyUpgraded = "read:project"
	GetConfigurationResponseBodyUpgradedReadWriteProject                  GetConfigurationResponseBodyUpgraded = "read-write:project"
	GetConfigurationResponseBodyUpgradedReadWriteProjectEnvVars           GetConfigurationResponseBodyUpgraded = "read-write:project-env-vars"
	GetConfigurationResponseBodyUpgradedReadWriteGlobalProjectEnvVars     GetConfigurationResponseBodyUpgraded = "read-write:global-project-env-vars"
	GetConfigurationResponseBodyUpgradedReadTeam                          GetConfigurationResponseBodyUpgraded = "read:team"
	GetConfigurationResponseBodyUpgradedReadUser                          GetConfigurationResponseBodyUpgraded = "read:user"
	GetConfigurationResponseBodyUpgradedReadWriteLogDrain                 GetConfigurationResponseBodyUpgraded = "read-write:log-drain"
	GetConfigurationResponseBodyUpgradedReadDomain                        GetConfigurationResponseBodyUpgraded = "read:domain"
	GetConfigurationResponseBodyUpgradedReadWriteDomain                   GetConfigurationResponseBodyUpgraded = "read-write:domain"
	GetConfigurationResponseBodyUpgradedReadWriteEdgeConfig               GetConfigurationResponseBodyUpgraded = "read-write:edge-config"
	GetConfigurationResponseBodyUpgradedReadWriteOtelEndpoint             GetConfigurationResponseBodyUpgraded = "read-write:otel-endpoint"
	GetConfigurationResponseBodyUpgradedReadMonitoring                    GetConfigurationResponseBodyUpgraded = "read:monitoring"
	GetConfigurationResponseBodyUpgradedReadWriteIntegrationResource      GetConfigurationResponseBodyUpgraded = "read-write:integration-resource"
)

func (e GetConfigurationResponseBodyUpgraded) ToPointer() *GetConfigurationResponseBodyUpgraded {
	return &e
}
func (e *GetConfigurationResponseBodyUpgraded) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "read:integration-configuration":
		fallthrough
	case "read-write:integration-configuration":
		fallthrough
	case "read:deployment":
		fallthrough
	case "read-write:deployment":
		fallthrough
	case "read-write:deployment-check":
		fallthrough
	case "read:project":
		fallthrough
	case "read-write:project":
		fallthrough
	case "read-write:project-env-vars":
		fallthrough
	case "read-write:global-project-env-vars":
		fallthrough
	case "read:team":
		fallthrough
	case "read:user":
		fallthrough
	case "read-write:log-drain":
		fallthrough
	case "read:domain":
		fallthrough
	case "read-write:domain":
		fallthrough
	case "read-write:edge-config":
		fallthrough
	case "read-write:otel-endpoint":
		fallthrough
	case "read:monitoring":
		fallthrough
	case "read-write:integration-resource":
		*e = GetConfigurationResponseBodyUpgraded(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetConfigurationResponseBodyUpgraded: %v", v)
	}
}

type GetConfigurationResponseBodyScopes struct {
	Added    []GetConfigurationResponseBodyAdded    `json:"added"`
	Upgraded []GetConfigurationResponseBodyUpgraded `json:"upgraded"`
}

func (o *GetConfigurationResponseBodyScopes) GetAdded() []GetConfigurationResponseBodyAdded {
	if o == nil {
		return []GetConfigurationResponseBodyAdded{}
	}
	return o.Added
}

func (o *GetConfigurationResponseBodyScopes) GetUpgraded() []GetConfigurationResponseBodyUpgraded {
	if o == nil {
		return []GetConfigurationResponseBodyUpgraded{}
	}
	return o.Upgraded
}

type GetConfigurationResponseBodyScopesQueue struct {
	Scopes      GetConfigurationResponseBodyScopes `json:"scopes"`
	Note        string                             `json:"note"`
	RequestedAt float64                            `json:"requestedAt"`
	ConfirmedAt *float64                           `json:"confirmedAt,omitempty"`
}

func (o *GetConfigurationResponseBodyScopesQueue) GetScopes() GetConfigurationResponseBodyScopes {
	if o == nil {
		return GetConfigurationResponseBodyScopes{}
	}
	return o.Scopes
}

func (o *GetConfigurationResponseBodyScopesQueue) GetNote() string {
	if o == nil {
		return ""
	}
	return o.Note
}

func (o *GetConfigurationResponseBodyScopesQueue) GetRequestedAt() float64 {
	if o == nil {
		return 0.0
	}
	return o.RequestedAt
}

func (o *GetConfigurationResponseBodyScopesQueue) GetConfirmedAt() *float64 {
	if o == nil {
		return nil
	}
	return o.ConfirmedAt
}

type GetConfigurationResponseBodyDisabledReason string

const (
	GetConfigurationResponseBodyDisabledReasonDisabledByOwner          GetConfigurationResponseBodyDisabledReason = "disabled-by-owner"
	GetConfigurationResponseBodyDisabledReasonFeatureNotAvailable      GetConfigurationResponseBodyDisabledReason = "feature-not-available"
	GetConfigurationResponseBodyDisabledReasonDisabledByAdmin          GetConfigurationResponseBodyDisabledReason = "disabled-by-admin"
	GetConfigurationResponseBodyDisabledReasonOriginalOwnerLeftTheTeam GetConfigurationResponseBodyDisabledReason = "original-owner-left-the-team"
)

func (e GetConfigurationResponseBodyDisabledReason) ToPointer() *GetConfigurationResponseBodyDisabledReason {
	return &e
}
func (e *GetConfigurationResponseBodyDisabledReason) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "disabled-by-owner":
		fallthrough
	case "feature-not-available":
		fallthrough
	case "disabled-by-admin":
		fallthrough
	case "original-owner-left-the-team":
		*e = GetConfigurationResponseBodyDisabledReason(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetConfigurationResponseBodyDisabledReason: %v", v)
	}
}

// GetConfigurationResponseBodyInstallationType - Defines the installation type. - 'external' integrations are installed via the existing integrations flow - 'marketplace' integrations are natively installed: - when accepting the TOS of a partner during the store creation process - if undefined, assume 'external'
type GetConfigurationResponseBodyInstallationType string

const (
	GetConfigurationResponseBodyInstallationTypeMarketplace GetConfigurationResponseBodyInstallationType = "marketplace"
	GetConfigurationResponseBodyInstallationTypeExternal    GetConfigurationResponseBodyInstallationType = "external"
)

func (e GetConfigurationResponseBodyInstallationType) ToPointer() *GetConfigurationResponseBodyInstallationType {
	return &e
}
func (e *GetConfigurationResponseBodyInstallationType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "marketplace":
		fallthrough
	case "external":
		*e = GetConfigurationResponseBodyInstallationType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetConfigurationResponseBodyInstallationType: %v", v)
	}
}

// GetConfigurationResponseBody1 - The configuration with the provided id
type GetConfigurationResponseBody1 struct {
	// A timestamp that tells you when the configuration was installed successfully
	CompletedAt *float64 `json:"completedAt,omitempty"`
	// A timestamp that tells you when the configuration was created
	CreatedAt float64 `json:"createdAt"`
	// The unique identifier of the configuration
	ID string `json:"id"`
	// The unique identifier of the app the configuration was created for
	IntegrationID string `json:"integrationId"`
	// The user or team ID that owns the configuration
	OwnerID string `json:"ownerId"`
	// When a configuration is limited to access certain projects, this will contain each of the project ID it is allowed to access. If it is not defined, the configuration has full access.
	Projects []string `json:"projects,omitempty"`
	// Source defines where the configuration was installed from. It is used to analyze user engagement for integration installations in product metrics.
	Source               *GetConfigurationResponseBodySource `json:"source,omitempty"`
	RemovedLogDrainsAt   *float64                            `json:"removedLogDrainsAt,omitempty"`
	RemovedProjectEnvsAt *float64                            `json:"removedProjectEnvsAt,omitempty"`
	RemovedTokensAt      *float64                            `json:"removedTokensAt,omitempty"`
	RemovedWebhooksAt    *float64                            `json:"removedWebhooksAt,omitempty"`
	// The slug of the integration the configuration is created for.
	Slug string `json:"slug"`
	// When the configuration was created for a team, this will show the ID of the team.
	TeamID *string                          `json:"teamId,omitempty"`
	Type   GetConfigurationResponseBodyType `json:"type"`
	// A timestamp that tells you when the configuration was updated.
	UpdatedAt float64 `json:"updatedAt"`
	// The ID of the user that created the configuration.
	UserID string `json:"userId"`
	// The resources that are allowed to be accessed by the configuration.
	Scopes      []string                                  `json:"scopes"`
	ScopesQueue []GetConfigurationResponseBodyScopesQueue `json:"scopesQueue,omitempty"`
	// A timestamp that tells you when the configuration was disabled. Note: Configurations can be disabled when the associated user loses access to a team. They do not function during this time until the configuration is 'transferred', meaning the associated user is changed to one with access to the team.
	DisabledAt *float64 `json:"disabledAt,omitempty"`
	// A timestamp that tells you when the configuration was updated.
	DeletedAt      *float64                                    `json:"deletedAt,omitempty"`
	DisabledReason *GetConfigurationResponseBodyDisabledReason `json:"disabledReason,omitempty"`
	// A timestamp that tells you when the configuration was migrated as part of the Northstar migration. In the future, if we allow integration configurations to be transferred between teams, this field should be cleared upon transfer.
	NorthstarMigratedAt *float64 `json:"northstarMigratedAt,omitempty"`
	// Defines the installation type. - 'external' integrations are installed via the existing integrations flow - 'marketplace' integrations are natively installed: - when accepting the TOS of a partner during the store creation process - if undefined, assume 'external'
	InstallationType *GetConfigurationResponseBodyInstallationType `json:"installationType,omitempty"`
}

func (o *GetConfigurationResponseBody1) GetCompletedAt() *float64 {
	if o == nil {
		return nil
	}
	return o.CompletedAt
}

func (o *GetConfigurationResponseBody1) GetCreatedAt() float64 {
	if o == nil {
		return 0.0
	}
	return o.CreatedAt
}

func (o *GetConfigurationResponseBody1) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetConfigurationResponseBody1) GetIntegrationID() string {
	if o == nil {
		return ""
	}
	return o.IntegrationID
}

func (o *GetConfigurationResponseBody1) GetOwnerID() string {
	if o == nil {
		return ""
	}
	return o.OwnerID
}

func (o *GetConfigurationResponseBody1) GetProjects() []string {
	if o == nil {
		return nil
	}
	return o.Projects
}

func (o *GetConfigurationResponseBody1) GetSource() *GetConfigurationResponseBodySource {
	if o == nil {
		return nil
	}
	return o.Source
}

func (o *GetConfigurationResponseBody1) GetRemovedLogDrainsAt() *float64 {
	if o == nil {
		return nil
	}
	return o.RemovedLogDrainsAt
}

func (o *GetConfigurationResponseBody1) GetRemovedProjectEnvsAt() *float64 {
	if o == nil {
		return nil
	}
	return o.RemovedProjectEnvsAt
}

func (o *GetConfigurationResponseBody1) GetRemovedTokensAt() *float64 {
	if o == nil {
		return nil
	}
	return o.RemovedTokensAt
}

func (o *GetConfigurationResponseBody1) GetRemovedWebhooksAt() *float64 {
	if o == nil {
		return nil
	}
	return o.RemovedWebhooksAt
}

func (o *GetConfigurationResponseBody1) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *GetConfigurationResponseBody1) GetTeamID() *string {
	if o == nil {
		return nil
	}
	return o.TeamID
}

func (o *GetConfigurationResponseBody1) GetType() GetConfigurationResponseBodyType {
	if o == nil {
		return GetConfigurationResponseBodyType("")
	}
	return o.Type
}

func (o *GetConfigurationResponseBody1) GetUpdatedAt() float64 {
	if o == nil {
		return 0.0
	}
	return o.UpdatedAt
}

func (o *GetConfigurationResponseBody1) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}

func (o *GetConfigurationResponseBody1) GetScopes() []string {
	if o == nil {
		return []string{}
	}
	return o.Scopes
}

func (o *GetConfigurationResponseBody1) GetScopesQueue() []GetConfigurationResponseBodyScopesQueue {
	if o == nil {
		return nil
	}
	return o.ScopesQueue
}

func (o *GetConfigurationResponseBody1) GetDisabledAt() *float64 {
	if o == nil {
		return nil
	}
	return o.DisabledAt
}

func (o *GetConfigurationResponseBody1) GetDeletedAt() *float64 {
	if o == nil {
		return nil
	}
	return o.DeletedAt
}

func (o *GetConfigurationResponseBody1) GetDisabledReason() *GetConfigurationResponseBodyDisabledReason {
	if o == nil {
		return nil
	}
	return o.DisabledReason
}

func (o *GetConfigurationResponseBody1) GetNorthstarMigratedAt() *float64 {
	if o == nil {
		return nil
	}
	return o.NorthstarMigratedAt
}

func (o *GetConfigurationResponseBody1) GetInstallationType() *GetConfigurationResponseBodyInstallationType {
	if o == nil {
		return nil
	}
	return o.InstallationType
}

type GetConfigurationResponseBodyUnionType string

const (
	GetConfigurationResponseBodyUnionTypeGetConfigurationResponseBody1 GetConfigurationResponseBodyUnionType = "getConfiguration_responseBody_1"
	GetConfigurationResponseBodyUnionTypeGetConfigurationResponseBody2 GetConfigurationResponseBodyUnionType = "getConfiguration_responseBody_2"
)

// GetConfigurationResponseBody - The configuration with the provided id
type GetConfigurationResponseBody struct {
	GetConfigurationResponseBody1 *GetConfigurationResponseBody1
	GetConfigurationResponseBody2 *GetConfigurationResponseBody2

	Type GetConfigurationResponseBodyUnionType
}

func CreateGetConfigurationResponseBodyGetConfigurationResponseBody1(getConfigurationResponseBody1 GetConfigurationResponseBody1) GetConfigurationResponseBody {
	typ := GetConfigurationResponseBodyUnionTypeGetConfigurationResponseBody1

	return GetConfigurationResponseBody{
		GetConfigurationResponseBody1: &getConfigurationResponseBody1,
		Type:                          typ,
	}
}

func CreateGetConfigurationResponseBodyGetConfigurationResponseBody2(getConfigurationResponseBody2 GetConfigurationResponseBody2) GetConfigurationResponseBody {
	typ := GetConfigurationResponseBodyUnionTypeGetConfigurationResponseBody2

	return GetConfigurationResponseBody{
		GetConfigurationResponseBody2: &getConfigurationResponseBody2,
		Type:                          typ,
	}
}

func (u *GetConfigurationResponseBody) UnmarshalJSON(data []byte) error {

	var getConfigurationResponseBody1 GetConfigurationResponseBody1 = GetConfigurationResponseBody1{}
	if err := utils.UnmarshalJSON(data, &getConfigurationResponseBody1, "", true, true); err == nil {
		u.GetConfigurationResponseBody1 = &getConfigurationResponseBody1
		u.Type = GetConfigurationResponseBodyUnionTypeGetConfigurationResponseBody1
		return nil
	}

	var getConfigurationResponseBody2 GetConfigurationResponseBody2 = GetConfigurationResponseBody2{}
	if err := utils.UnmarshalJSON(data, &getConfigurationResponseBody2, "", true, true); err == nil {
		u.GetConfigurationResponseBody2 = &getConfigurationResponseBody2
		u.Type = GetConfigurationResponseBodyUnionTypeGetConfigurationResponseBody2
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetConfigurationResponseBody", string(data))
}

func (u GetConfigurationResponseBody) MarshalJSON() ([]byte, error) {
	if u.GetConfigurationResponseBody1 != nil {
		return utils.MarshalJSON(u.GetConfigurationResponseBody1, "", true)
	}

	if u.GetConfigurationResponseBody2 != nil {
		return utils.MarshalJSON(u.GetConfigurationResponseBody2, "", true)
	}

	return nil, errors.New("could not marshal union type GetConfigurationResponseBody: all fields are null")
}

type GetConfigurationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The configuration with the provided id
	OneOf *GetConfigurationResponseBody
}

func (o *GetConfigurationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetConfigurationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetConfigurationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetConfigurationResponse) GetOneOf() *GetConfigurationResponseBody {
	if o == nil {
		return nil
	}
	return o.OneOf
}
