// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/vercel/terraform-provider-vercel/internal/sdk/models/shared"
	"net/http"
)

type ListDeploymentFilesRequest struct {
	// The unique deployment identifier
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// The Team identifier to perform the request on behalf of.
	TeamID *string `queryParam:"style=form,explode=true,name=teamId"`
	// The Team slug to perform the request on behalf of.
	Slug *string `queryParam:"style=form,explode=true,name=slug"`
}

func (o *ListDeploymentFilesRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ListDeploymentFilesRequest) GetTeamID() *string {
	if o == nil {
		return nil
	}
	return o.TeamID
}

func (o *ListDeploymentFilesRequest) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

type ListDeploymentFilesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Retrieved the file tree successfully
	FileTrees []shared.FileTree
}

func (o *ListDeploymentFilesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListDeploymentFilesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListDeploymentFilesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListDeploymentFilesResponse) GetFileTrees() []shared.FileTree {
	if o == nil {
		return nil
	}
	return o.FileTrees
}
