// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EdgeConfigItem - The EdgeConfig.
type EdgeConfigItem struct {
	CreatedAt    int64                `json:"createdAt"`
	EdgeConfigID string               `json:"edgeConfigId"`
	Key          string               `json:"key"`
	UpdatedAt    int64                `json:"updatedAt"`
	Value        *EdgeConfigItemValue `json:"value"`
}

func (o *EdgeConfigItem) GetCreatedAt() int64 {
	if o == nil {
		return 0
	}
	return o.CreatedAt
}

func (o *EdgeConfigItem) GetEdgeConfigID() string {
	if o == nil {
		return ""
	}
	return o.EdgeConfigID
}

func (o *EdgeConfigItem) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *EdgeConfigItem) GetUpdatedAt() int64 {
	if o == nil {
		return 0
	}
	return o.UpdatedAt
}

func (o *EdgeConfigItem) GetValue() *EdgeConfigItemValue {
	if o == nil {
		return nil
	}
	return o.Value
}
