workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    vercel-api:
        inputs:
            - location: ./vercel-api.yaml
        overlays:
            - location: ./overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/vercel/vercel/vercel-api
targets:
    Vercel-Terraform:
        target: terraform
        source: vercel-api
