// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/speakeasy/terraform-provider-terraform/internal/sdk/models/shared"
)

func (r *TeamDataSourceModel) RefreshFromSharedTeam(resp *shared.Team) {
	if resp != nil {
	}
}
