// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type CreateProjectTarget struct {
	ArrayOfTwo []types.String `tfsdk:"array_of_two" tfPlanOnly:"true"`
	One        types.String   `tfsdk:"one" tfPlanOnly:"true"`
}
