// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

type CreateProjectContentHint struct {
	One      *CreateProjectContentHint1  `tfsdk:"one" tfPlanOnly:"true"`
	Ten      *CreateProjectContentHint10 `tfsdk:"ten" tfPlanOnly:"true"`
	Eleven   *ContentHint11              `tfsdk:"eleven" tfPlanOnly:"true"`
	Twelve   *ContentHint12              `tfsdk:"twelve" tfPlanOnly:"true"`
	Thirteen *ContentHint13              `tfsdk:"thirteen" tfPlanOnly:"true"`
	Fourteen *ContentHint14              `tfsdk:"fourteen" tfPlanOnly:"true"`
	Two      *CreateProjectContentHint2  `tfsdk:"two" tfPlanOnly:"true"`
	Three    *CreateProjectContentHint3  `tfsdk:"three" tfPlanOnly:"true"`
	Four     *CreateProjectContentHint4  `tfsdk:"four" tfPlanOnly:"true"`
	Five     *CreateProjectContentHint5  `tfsdk:"five" tfPlanOnly:"true"`
	Six      *CreateProjectContentHint6  `tfsdk:"six" tfPlanOnly:"true"`
	Seven    *CreateProjectContentHint7  `tfsdk:"seven" tfPlanOnly:"true"`
	Eight    *CreateProjectContentHint8  `tfsdk:"eight" tfPlanOnly:"true"`
	Nine     *CreateProjectContentHint9  `tfsdk:"nine" tfPlanOnly:"true"`
}
