// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type GetDeployment2 struct {
	Alias                   []types.String                `tfsdk:"alias"`
	AliasAssigned           types.Bool                    `tfsdk:"alias_assigned"`
	AliasError              *CreateDeploymentAliasError   `tfsdk:"alias_error"`
	AliasFinal              types.String                  `tfsdk:"alias_final"`
	AliasWarning            *CreateDeploymentAliasWarning `tfsdk:"alias_warning"`
	AutoAssignCustomDomains types.Bool                    `tfsdk:"auto_assign_custom_domains"`
	AutomaticAliases        []types.String                `tfsdk:"automatic_aliases"`
	BootedAt                types.Number                  `tfsdk:"booted_at"`
	BuildErrorAt            types.Number                  `tfsdk:"build_error_at"`
	BuildingAt              types.Number                  `tfsdk:"building_at"`
	CanceledAt              types.Number                  `tfsdk:"canceled_at"`
	ChecksConclusion        types.String                  `tfsdk:"checks_conclusion"`
	ChecksState             types.String                  `tfsdk:"checks_state"`
	CreatedAt               types.Number                  `tfsdk:"created_at"`
	Creator                 CreateDeploymentCreator       `tfsdk:"creator"`
	ErrorCode               types.String                  `tfsdk:"error_code"`
	ErrorLink               types.String                  `tfsdk:"error_link"`
	ErrorMessage            types.String                  `tfsdk:"error_message"`
	ErrorStep               types.String                  `tfsdk:"error_step"`
	GitSource               *GetDeploymentGitSource       `tfsdk:"git_source"`
	ID                      types.String                  `tfsdk:"id"`
	Lambdas                 []CreateDeploymentLambdas     `tfsdk:"lambdas"`
	Meta                    map[string]types.String       `tfsdk:"meta"`
	Name                    types.String                  `tfsdk:"name"`
	PassiveRegions          []types.String                `tfsdk:"passive_regions"`
	PreviewCommentsEnabled  types.Bool                    `tfsdk:"preview_comments_enabled"`
	Project                 *GetDeploymentProject         `tfsdk:"project"`
	Public                  types.Bool                    `tfsdk:"public"`
	ReadyState              types.String                  `tfsdk:"ready_state"`
	ReadySubstate           types.String                  `tfsdk:"ready_substate"`
	Regions                 []types.String                `tfsdk:"regions"`
	Source                  types.String                  `tfsdk:"source"`
	Target                  types.String                  `tfsdk:"target"`
	Team                    *GetDeploymentTeam            `tfsdk:"team"`
	Type                    types.String                  `tfsdk:"type"`
	URL                     types.String                  `tfsdk:"url"`
	UserAliases             []types.String                `tfsdk:"user_aliases"`
	Version                 types.Number                  `tfsdk:"version"`
}
