// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type GetProjectEnv struct {
	Comment             types.String                   `tfsdk:"comment"`
	ConfigurationID     types.String                   `tfsdk:"configuration_id"`
	ContentHint         *GetProjectContentHint         `tfsdk:"content_hint"`
	CreatedAt           types.Number                   `tfsdk:"created_at"`
	CreatedBy           types.String                   `tfsdk:"created_by"`
	CustomEnvironmentID types.String                   `tfsdk:"custom_environment_id"`
	Decrypted           types.Bool                     `tfsdk:"decrypted"`
	EdgeConfigID        types.String                   `tfsdk:"edge_config_id"`
	EdgeConfigTokenID   types.String                   `tfsdk:"edge_config_token_id"`
	GitBranch           types.String                   `tfsdk:"git_branch"`
	ID                  types.String                   `tfsdk:"id"`
	InternalContentHint *GetProjectInternalContentHint `tfsdk:"internal_content_hint"`
	Key                 types.String                   `tfsdk:"key"`
	Target              []types.String                 `tfsdk:"target"`
	Type                types.String                   `tfsdk:"type"`
	UpdatedAt           types.Number                   `tfsdk:"updated_at"`
	UpdatedBy           types.String                   `tfsdk:"updated_by"`
	Value               types.String                   `tfsdk:"value"`
}
