// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type GetDeploymentRoutes3 struct {
	Src        types.String `tfsdk:"src"`
	Continue   types.Bool   `tfsdk:"continue"`
	Middleware types.Number `tfsdk:"middleware"`
}
