// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CreateEdgeConfigTokenRequestBody struct {
	Label string `json:"label"`
}

type CreateEdgeConfigTokenRequest struct {
	RequestBody  *CreateEdgeConfigTokenRequestBody `request:"mediaType=application/json"`
	EdgeConfigID string                            `pathParam:"style=simple,explode=false,name=edgeConfigId"`
	// The Team identifier or slug to perform the request on behalf of.
	TeamID *string `queryParam:"style=form,explode=true,name=teamId"`
}

type CreateEdgeConfigToken201ApplicationJSON struct {
	ID    string `json:"id"`
	Token string `json:"token"`
}

type CreateEdgeConfigTokenResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse                                   *http.Response
	CreateEdgeConfigToken201ApplicationJSONObject *CreateEdgeConfigToken201ApplicationJSON
}
