// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteDomainRequest struct {
	// The name of the domain.
	Domain string `pathParam:"style=simple,explode=false,name=domain"`
	// The Team identifier or slug to perform the request on behalf of.
	TeamID *string `queryParam:"style=form,explode=true,name=teamId"`
}

// DeleteDomain200ApplicationJSON - Successful response removing a domain.
type DeleteDomain200ApplicationJSON struct {
	UID string `json:"uid"`
}

type DeleteDomainResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response removing a domain.
	DeleteDomain200ApplicationJSONObject *DeleteDomain200ApplicationJSON
}
