// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/zchee/terraform-provider-vercel/internal/sdk/pkg/models/shared"
	"github.com/zchee/terraform-provider-vercel/internal/sdk/pkg/utils"
	"net/http"
)

// QueryParamTarget - Filter deployments based on the environment.
type QueryParamTarget string

const (
	QueryParamTargetProduction QueryParamTarget = "production"
	QueryParamTargetPreview    QueryParamTarget = "preview"
)

func (e QueryParamTarget) ToPointer() *QueryParamTarget {
	return &e
}

func (e *QueryParamTarget) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "production":
		fallthrough
	case "preview":
		*e = QueryParamTarget(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParamTarget: %v", v)
	}
}

type GetDeploymentsRequest struct {
	// Name of the deployment.
	App *string `queryParam:"style=form,explode=true,name=app"`
	// Gets the deployment created after this Date timestamp. (default: current time)
	From *int64 `queryParam:"style=form,explode=true,name=from"`
	// Maximum number of deployments to list from a request.
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Filter deployments from the given `projectId`.
	ProjectID *string `queryParam:"style=form,explode=true,name=projectId"`
	// Filter deployments based on their rollback candidacy
	RollbackCandidate *bool `queryParam:"style=form,explode=true,name=rollbackCandidate"`
	// Get Deployments created after this JavaScript timestamp.
	Since *int64 `queryParam:"style=form,explode=true,name=since"`
	// Filter deployments based on their state (`BUILDING`, `ERROR`, `INITIALIZING`, `QUEUED`, `READY`, `CANCELED`)
	State *string `queryParam:"style=form,explode=true,name=state"`
	// Filter deployments based on the environment.
	Target *QueryParamTarget `queryParam:"style=form,explode=true,name=target"`
	// The Team identifier or slug to perform the request on behalf of.
	TeamID *string `queryParam:"style=form,explode=true,name=teamId"`
	// Gets the deployment created before this Date timestamp. (default: current time)
	To *int64 `queryParam:"style=form,explode=true,name=to"`
	// Get Deployments created before this JavaScript timestamp.
	Until *int64 `queryParam:"style=form,explode=true,name=until"`
	// Filter out deployments based on users who have created the deployment.
	Users *string `queryParam:"style=form,explode=true,name=users"`
}

func (o *GetDeploymentsRequest) GetApp() *string {
	if o == nil {
		return nil
	}
	return o.App
}

func (o *GetDeploymentsRequest) GetFrom() *int64 {
	if o == nil {
		return nil
	}
	return o.From
}

func (o *GetDeploymentsRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *GetDeploymentsRequest) GetProjectID() *string {
	if o == nil {
		return nil
	}
	return o.ProjectID
}

func (o *GetDeploymentsRequest) GetRollbackCandidate() *bool {
	if o == nil {
		return nil
	}
	return o.RollbackCandidate
}

func (o *GetDeploymentsRequest) GetSince() *int64 {
	if o == nil {
		return nil
	}
	return o.Since
}

func (o *GetDeploymentsRequest) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *GetDeploymentsRequest) GetTarget() *QueryParamTarget {
	if o == nil {
		return nil
	}
	return o.Target
}

func (o *GetDeploymentsRequest) GetTeamID() *string {
	if o == nil {
		return nil
	}
	return o.TeamID
}

func (o *GetDeploymentsRequest) GetTo() *int64 {
	if o == nil {
		return nil
	}
	return o.To
}

func (o *GetDeploymentsRequest) GetUntil() *int64 {
	if o == nil {
		return nil
	}
	return o.Until
}

func (o *GetDeploymentsRequest) GetUsers() *string {
	if o == nil {
		return nil
	}
	return o.Users
}

type AliasAssignedType string

const (
	AliasAssignedTypeInteger AliasAssignedType = "integer"
	AliasAssignedTypeBoolean AliasAssignedType = "boolean"
)

type AliasAssigned struct {
	Integer *int64
	Boolean *bool

	Type AliasAssignedType
}

func CreateAliasAssignedInteger(integer int64) AliasAssigned {
	typ := AliasAssignedTypeInteger

	return AliasAssigned{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateAliasAssignedBoolean(boolean bool) AliasAssigned {
	typ := AliasAssignedTypeBoolean

	return AliasAssigned{
		Boolean: &boolean,
		Type:    typ,
	}
}

func (u *AliasAssigned) UnmarshalJSON(data []byte) error {

	integer := new(int64)
	if err := utils.UnmarshalJSON(data, &integer, "", true, true); err == nil {
		u.Integer = integer
		u.Type = AliasAssignedTypeInteger
		return nil
	}

	boolean := new(bool)
	if err := utils.UnmarshalJSON(data, &boolean, "", true, true); err == nil {
		u.Boolean = boolean
		u.Type = AliasAssignedTypeBoolean
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u AliasAssigned) MarshalJSON() ([]byte, error) {
	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}

// GetDeploymentsAliasError - An error object in case aliasing of the deployment failed.
type GetDeploymentsAliasError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (o *GetDeploymentsAliasError) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *GetDeploymentsAliasError) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// GetDeploymentsChecksConclusion - Conclusion for checks
type GetDeploymentsChecksConclusion string

const (
	GetDeploymentsChecksConclusionSucceeded GetDeploymentsChecksConclusion = "succeeded"
	GetDeploymentsChecksConclusionFailed    GetDeploymentsChecksConclusion = "failed"
	GetDeploymentsChecksConclusionSkipped   GetDeploymentsChecksConclusion = "skipped"
	GetDeploymentsChecksConclusionCanceled  GetDeploymentsChecksConclusion = "canceled"
)

func (e GetDeploymentsChecksConclusion) ToPointer() *GetDeploymentsChecksConclusion {
	return &e
}

func (e *GetDeploymentsChecksConclusion) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "succeeded":
		fallthrough
	case "failed":
		fallthrough
	case "skipped":
		fallthrough
	case "canceled":
		*e = GetDeploymentsChecksConclusion(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetDeploymentsChecksConclusion: %v", v)
	}
}

// GetDeploymentsChecksState - State of all registered checks
type GetDeploymentsChecksState string

const (
	GetDeploymentsChecksStateRegistered GetDeploymentsChecksState = "registered"
	GetDeploymentsChecksStateRunning    GetDeploymentsChecksState = "running"
	GetDeploymentsChecksStateCompleted  GetDeploymentsChecksState = "completed"
)

func (e GetDeploymentsChecksState) ToPointer() *GetDeploymentsChecksState {
	return &e
}

func (e *GetDeploymentsChecksState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "registered":
		fallthrough
	case "running":
		fallthrough
	case "completed":
		*e = GetDeploymentsChecksState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetDeploymentsChecksState: %v", v)
	}
}

// GetDeploymentsCreator - Metadata information of the user who created the deployment.
type GetDeploymentsCreator struct {
	// The email address of the user.
	Email *string `json:"email,omitempty"`
	// The GitHub login of the user.
	GithubLogin *string `json:"githubLogin,omitempty"`
	// The GitLab login of the user.
	GitlabLogin *string `json:"gitlabLogin,omitempty"`
	// The unique identifier of the user.
	UID string `json:"uid"`
	// The username of the user.
	Username *string `json:"username,omitempty"`
}

func (o *GetDeploymentsCreator) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *GetDeploymentsCreator) GetGithubLogin() *string {
	if o == nil {
		return nil
	}
	return o.GithubLogin
}

func (o *GetDeploymentsCreator) GetGitlabLogin() *string {
	if o == nil {
		return nil
	}
	return o.GitlabLogin
}

func (o *GetDeploymentsCreator) GetUID() string {
	if o == nil {
		return ""
	}
	return o.UID
}

func (o *GetDeploymentsCreator) GetUsername() *string {
	if o == nil {
		return nil
	}
	return o.Username
}

type GetDeploymentsFramework string

const (
	GetDeploymentsFrameworkBlitzjs        GetDeploymentsFramework = "blitzjs"
	GetDeploymentsFrameworkNextjs         GetDeploymentsFramework = "nextjs"
	GetDeploymentsFrameworkGatsby         GetDeploymentsFramework = "gatsby"
	GetDeploymentsFrameworkRemix          GetDeploymentsFramework = "remix"
	GetDeploymentsFrameworkAstro          GetDeploymentsFramework = "astro"
	GetDeploymentsFrameworkHexo           GetDeploymentsFramework = "hexo"
	GetDeploymentsFrameworkEleventy       GetDeploymentsFramework = "eleventy"
	GetDeploymentsFrameworkDocusaurus2    GetDeploymentsFramework = "docusaurus-2"
	GetDeploymentsFrameworkDocusaurus     GetDeploymentsFramework = "docusaurus"
	GetDeploymentsFrameworkPreact         GetDeploymentsFramework = "preact"
	GetDeploymentsFrameworkSolidstart     GetDeploymentsFramework = "solidstart"
	GetDeploymentsFrameworkDojo           GetDeploymentsFramework = "dojo"
	GetDeploymentsFrameworkEmber          GetDeploymentsFramework = "ember"
	GetDeploymentsFrameworkVue            GetDeploymentsFramework = "vue"
	GetDeploymentsFrameworkScully         GetDeploymentsFramework = "scully"
	GetDeploymentsFrameworkIonicAngular   GetDeploymentsFramework = "ionic-angular"
	GetDeploymentsFrameworkAngular        GetDeploymentsFramework = "angular"
	GetDeploymentsFrameworkPolymer        GetDeploymentsFramework = "polymer"
	GetDeploymentsFrameworkSvelte         GetDeploymentsFramework = "svelte"
	GetDeploymentsFrameworkSveltekit      GetDeploymentsFramework = "sveltekit"
	GetDeploymentsFrameworkSveltekit1     GetDeploymentsFramework = "sveltekit-1"
	GetDeploymentsFrameworkIonicReact     GetDeploymentsFramework = "ionic-react"
	GetDeploymentsFrameworkCreateReactApp GetDeploymentsFramework = "create-react-app"
	GetDeploymentsFrameworkGridsome       GetDeploymentsFramework = "gridsome"
	GetDeploymentsFrameworkUmijs          GetDeploymentsFramework = "umijs"
	GetDeploymentsFrameworkSapper         GetDeploymentsFramework = "sapper"
	GetDeploymentsFrameworkSaber          GetDeploymentsFramework = "saber"
	GetDeploymentsFrameworkStencil        GetDeploymentsFramework = "stencil"
	GetDeploymentsFrameworkNuxtjs         GetDeploymentsFramework = "nuxtjs"
	GetDeploymentsFrameworkRedwoodjs      GetDeploymentsFramework = "redwoodjs"
	GetDeploymentsFrameworkHugo           GetDeploymentsFramework = "hugo"
	GetDeploymentsFrameworkJekyll         GetDeploymentsFramework = "jekyll"
	GetDeploymentsFrameworkBrunch         GetDeploymentsFramework = "brunch"
	GetDeploymentsFrameworkMiddleman      GetDeploymentsFramework = "middleman"
	GetDeploymentsFrameworkZola           GetDeploymentsFramework = "zola"
	GetDeploymentsFrameworkHydrogen       GetDeploymentsFramework = "hydrogen"
	GetDeploymentsFrameworkVite           GetDeploymentsFramework = "vite"
	GetDeploymentsFrameworkVitepress      GetDeploymentsFramework = "vitepress"
	GetDeploymentsFrameworkVuepress       GetDeploymentsFramework = "vuepress"
	GetDeploymentsFrameworkParcel         GetDeploymentsFramework = "parcel"
	GetDeploymentsFrameworkSanity         GetDeploymentsFramework = "sanity"
	GetDeploymentsFrameworkStorybook      GetDeploymentsFramework = "storybook"
)

func (e GetDeploymentsFramework) ToPointer() *GetDeploymentsFramework {
	return &e
}

func (e *GetDeploymentsFramework) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "blitzjs":
		fallthrough
	case "nextjs":
		fallthrough
	case "gatsby":
		fallthrough
	case "remix":
		fallthrough
	case "astro":
		fallthrough
	case "hexo":
		fallthrough
	case "eleventy":
		fallthrough
	case "docusaurus-2":
		fallthrough
	case "docusaurus":
		fallthrough
	case "preact":
		fallthrough
	case "solidstart":
		fallthrough
	case "dojo":
		fallthrough
	case "ember":
		fallthrough
	case "vue":
		fallthrough
	case "scully":
		fallthrough
	case "ionic-angular":
		fallthrough
	case "angular":
		fallthrough
	case "polymer":
		fallthrough
	case "svelte":
		fallthrough
	case "sveltekit":
		fallthrough
	case "sveltekit-1":
		fallthrough
	case "ionic-react":
		fallthrough
	case "create-react-app":
		fallthrough
	case "gridsome":
		fallthrough
	case "umijs":
		fallthrough
	case "sapper":
		fallthrough
	case "saber":
		fallthrough
	case "stencil":
		fallthrough
	case "nuxtjs":
		fallthrough
	case "redwoodjs":
		fallthrough
	case "hugo":
		fallthrough
	case "jekyll":
		fallthrough
	case "brunch":
		fallthrough
	case "middleman":
		fallthrough
	case "zola":
		fallthrough
	case "hydrogen":
		fallthrough
	case "vite":
		fallthrough
	case "vitepress":
		fallthrough
	case "vuepress":
		fallthrough
	case "parcel":
		fallthrough
	case "sanity":
		fallthrough
	case "storybook":
		*e = GetDeploymentsFramework(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetDeploymentsFramework: %v", v)
	}
}

// GetDeploymentsGitComments - Since June '23
type GetDeploymentsGitComments struct {
	// Whether the Vercel bot should comment on commits
	OnCommit bool `json:"onCommit"`
	// Whether the Vercel bot should comment on PRs
	OnPullRequest bool `json:"onPullRequest"`
}

func (o *GetDeploymentsGitComments) GetOnCommit() bool {
	if o == nil {
		return false
	}
	return o.OnCommit
}

func (o *GetDeploymentsGitComments) GetOnPullRequest() bool {
	if o == nil {
		return false
	}
	return o.OnPullRequest
}

type GetDeploymentsNodeVersion string

const (
	GetDeploymentsNodeVersionEighteenX GetDeploymentsNodeVersion = "18.x"
	GetDeploymentsNodeVersionSixteenX  GetDeploymentsNodeVersion = "16.x"
	GetDeploymentsNodeVersionFourteenX GetDeploymentsNodeVersion = "14.x"
	GetDeploymentsNodeVersionTwelveX   GetDeploymentsNodeVersion = "12.x"
	GetDeploymentsNodeVersionTenX      GetDeploymentsNodeVersion = "10.x"
)

func (e GetDeploymentsNodeVersion) ToPointer() *GetDeploymentsNodeVersion {
	return &e
}

func (e *GetDeploymentsNodeVersion) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "18.x":
		fallthrough
	case "16.x":
		fallthrough
	case "14.x":
		fallthrough
	case "12.x":
		fallthrough
	case "10.x":
		*e = GetDeploymentsNodeVersion(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetDeploymentsNodeVersion: %v", v)
	}
}

// GetDeploymentsProjectSettings - The project settings which was used for this deployment
type GetDeploymentsProjectSettings struct {
	BuildCommand                  *string                  `json:"buildCommand,omitempty"`
	CommandForIgnoringBuildStep   *string                  `json:"commandForIgnoringBuildStep,omitempty"`
	CreatedAt                     *int64                   `json:"createdAt,omitempty"`
	CustomerSupportCodeVisibility *bool                    `json:"customerSupportCodeVisibility,omitempty"`
	DevCommand                    *string                  `json:"devCommand,omitempty"`
	Framework                     *GetDeploymentsFramework `json:"framework,omitempty"`
	// Since June '23
	GitComments                     *GetDeploymentsGitComments `json:"gitComments,omitempty"`
	GitForkProtection               *bool                      `json:"gitForkProtection,omitempty"`
	GitLFS                          *bool                      `json:"gitLFS,omitempty"`
	InstallCommand                  *string                    `json:"installCommand,omitempty"`
	NodeVersion                     *GetDeploymentsNodeVersion `json:"nodeVersion,omitempty"`
	OutputDirectory                 *string                    `json:"outputDirectory,omitempty"`
	PublicSource                    *bool                      `json:"publicSource,omitempty"`
	RootDirectory                   *string                    `json:"rootDirectory,omitempty"`
	ServerlessFunctionRegion        *string                    `json:"serverlessFunctionRegion,omitempty"`
	SkipGitConnectDuringLink        *bool                      `json:"skipGitConnectDuringLink,omitempty"`
	SourceFilesOutsideRootDirectory *bool                      `json:"sourceFilesOutsideRootDirectory,omitempty"`
}

func (o *GetDeploymentsProjectSettings) GetBuildCommand() *string {
	if o == nil {
		return nil
	}
	return o.BuildCommand
}

func (o *GetDeploymentsProjectSettings) GetCommandForIgnoringBuildStep() *string {
	if o == nil {
		return nil
	}
	return o.CommandForIgnoringBuildStep
}

func (o *GetDeploymentsProjectSettings) GetCreatedAt() *int64 {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *GetDeploymentsProjectSettings) GetCustomerSupportCodeVisibility() *bool {
	if o == nil {
		return nil
	}
	return o.CustomerSupportCodeVisibility
}

func (o *GetDeploymentsProjectSettings) GetDevCommand() *string {
	if o == nil {
		return nil
	}
	return o.DevCommand
}

func (o *GetDeploymentsProjectSettings) GetFramework() *GetDeploymentsFramework {
	if o == nil {
		return nil
	}
	return o.Framework
}

func (o *GetDeploymentsProjectSettings) GetGitComments() *GetDeploymentsGitComments {
	if o == nil {
		return nil
	}
	return o.GitComments
}

func (o *GetDeploymentsProjectSettings) GetGitForkProtection() *bool {
	if o == nil {
		return nil
	}
	return o.GitForkProtection
}

func (o *GetDeploymentsProjectSettings) GetGitLFS() *bool {
	if o == nil {
		return nil
	}
	return o.GitLFS
}

func (o *GetDeploymentsProjectSettings) GetInstallCommand() *string {
	if o == nil {
		return nil
	}
	return o.InstallCommand
}

func (o *GetDeploymentsProjectSettings) GetNodeVersion() *GetDeploymentsNodeVersion {
	if o == nil {
		return nil
	}
	return o.NodeVersion
}

func (o *GetDeploymentsProjectSettings) GetOutputDirectory() *string {
	if o == nil {
		return nil
	}
	return o.OutputDirectory
}

func (o *GetDeploymentsProjectSettings) GetPublicSource() *bool {
	if o == nil {
		return nil
	}
	return o.PublicSource
}

func (o *GetDeploymentsProjectSettings) GetRootDirectory() *string {
	if o == nil {
		return nil
	}
	return o.RootDirectory
}

func (o *GetDeploymentsProjectSettings) GetServerlessFunctionRegion() *string {
	if o == nil {
		return nil
	}
	return o.ServerlessFunctionRegion
}

func (o *GetDeploymentsProjectSettings) GetSkipGitConnectDuringLink() *bool {
	if o == nil {
		return nil
	}
	return o.SkipGitConnectDuringLink
}

func (o *GetDeploymentsProjectSettings) GetSourceFilesOutsideRootDirectory() *bool {
	if o == nil {
		return nil
	}
	return o.SourceFilesOutsideRootDirectory
}

// GetDeploymentsReadySubstate - Since June 2023 Substate of deployment when readyState is 'READY' Tracks whether or not deployment has seen production traffic: - STAGED: never seen production traffic - PROMOTED: has seen production traffic
type GetDeploymentsReadySubstate string

const (
	GetDeploymentsReadySubstateStaged   GetDeploymentsReadySubstate = "STAGED"
	GetDeploymentsReadySubstatePromoted GetDeploymentsReadySubstate = "PROMOTED"
)

func (e GetDeploymentsReadySubstate) ToPointer() *GetDeploymentsReadySubstate {
	return &e
}

func (e *GetDeploymentsReadySubstate) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "STAGED":
		fallthrough
	case "PROMOTED":
		*e = GetDeploymentsReadySubstate(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetDeploymentsReadySubstate: %v", v)
	}
}

// GetDeploymentsSource - The source of the deployment.
type GetDeploymentsSource string

const (
	GetDeploymentsSourceCli        GetDeploymentsSource = "cli"
	GetDeploymentsSourceGit        GetDeploymentsSource = "git"
	GetDeploymentsSourceImport     GetDeploymentsSource = "import"
	GetDeploymentsSourceImportRepo GetDeploymentsSource = "import/repo"
	GetDeploymentsSourceCloneRepo  GetDeploymentsSource = "clone/repo"
)

func (e GetDeploymentsSource) ToPointer() *GetDeploymentsSource {
	return &e
}

func (e *GetDeploymentsSource) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "cli":
		fallthrough
	case "git":
		fallthrough
	case "import":
		fallthrough
	case "import/repo":
		fallthrough
	case "clone/repo":
		*e = GetDeploymentsSource(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetDeploymentsSource: %v", v)
	}
}

// State - In which state is the deployment.
type State string

const (
	StateBuilding     State = "BUILDING"
	StateError        State = "ERROR"
	StateInitializing State = "INITIALIZING"
	StateQueued       State = "QUEUED"
	StateReady        State = "READY"
	StateCanceled     State = "CANCELED"
)

func (e State) ToPointer() *State {
	return &e
}

func (e *State) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "BUILDING":
		fallthrough
	case "ERROR":
		fallthrough
	case "INITIALIZING":
		fallthrough
	case "QUEUED":
		fallthrough
	case "READY":
		fallthrough
	case "CANCELED":
		*e = State(v)
		return nil
	default:
		return fmt.Errorf("invalid value for State: %v", v)
	}
}

// GetDeploymentsTarget - On which environment has the deployment been deployed to.
type GetDeploymentsTarget string

const (
	GetDeploymentsTargetProduction GetDeploymentsTarget = "production"
	GetDeploymentsTargetStaging    GetDeploymentsTarget = "staging"
)

func (e GetDeploymentsTarget) ToPointer() *GetDeploymentsTarget {
	return &e
}

func (e *GetDeploymentsTarget) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "production":
		fallthrough
	case "staging":
		*e = GetDeploymentsTarget(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetDeploymentsTarget: %v", v)
	}
}

// GetDeploymentsType - The type of the deployment.
type GetDeploymentsType string

const (
	GetDeploymentsTypeLambdas GetDeploymentsType = "LAMBDAS"
)

func (e GetDeploymentsType) ToPointer() *GetDeploymentsType {
	return &e
}

func (e *GetDeploymentsType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "LAMBDAS":
		*e = GetDeploymentsType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetDeploymentsType: %v", v)
	}
}

type Deployments struct {
	AliasAssigned *AliasAssigned `json:"aliasAssigned,omitempty"`
	// An error object in case aliasing of the deployment failed.
	AliasError *GetDeploymentsAliasError `json:"aliasError,omitempty"`
	// Timestamp of when the deployment started building at.
	BuildingAt *int64 `json:"buildingAt,omitempty"`
	// Conclusion for checks
	ChecksConclusion *GetDeploymentsChecksConclusion `json:"checksConclusion,omitempty"`
	// State of all registered checks
	ChecksState *GetDeploymentsChecksState `json:"checksState,omitempty"`
	// The flag saying if Vercel Connect configuration is used for builds
	ConnectBuildsEnabled *bool `json:"connectBuildsEnabled,omitempty"`
	// The ID of Vercel Connect configuration used for this deployment
	ConnectConfigurationID *string `json:"connectConfigurationId,omitempty"`
	// Timestamp of when the deployment got created.
	Created int64 `json:"created"`
	// Timestamp of when the deployment got created.
	CreatedAt *int64 `json:"createdAt,omitempty"`
	// Metadata information of the user who created the deployment.
	Creator GetDeploymentsCreator `json:"creator"`
	// Vercel URL to inspect the deployment.
	InspectorURL *string `json:"inspectorUrl"`
	// Deployment can be used for instant rollback
	IsRollbackCandidate *bool `json:"isRollbackCandidate,omitempty"`
	// Metadata information from the Git provider.
	Meta map[string]string `json:"meta,omitempty"`
	// The name of the deployment.
	Name string `json:"name"`
	// The project settings which was used for this deployment
	ProjectSettings *GetDeploymentsProjectSettings `json:"projectSettings,omitempty"`
	// Timestamp of when the deployment got ready.
	Ready *int64 `json:"ready,omitempty"`
	// Since June 2023 Substate of deployment when readyState is 'READY' Tracks whether or not deployment has seen production traffic: - STAGED: never seen production traffic - PROMOTED: has seen production traffic
	ReadySubstate *GetDeploymentsReadySubstate `json:"readySubstate,omitempty"`
	// The source of the deployment.
	Source *GetDeploymentsSource `json:"source,omitempty"`
	// In which state is the deployment.
	State *State `json:"state,omitempty"`
	// On which environment has the deployment been deployed to.
	Target *GetDeploymentsTarget `json:"target,omitempty"`
	// The type of the deployment.
	Type GetDeploymentsType `json:"type"`
	// The unique identifier of the deployment.
	UID string `json:"uid"`
	// The URL of the deployment.
	URL string `json:"url"`
}

func (o *Deployments) GetAliasAssigned() *AliasAssigned {
	if o == nil {
		return nil
	}
	return o.AliasAssigned
}

func (o *Deployments) GetAliasError() *GetDeploymentsAliasError {
	if o == nil {
		return nil
	}
	return o.AliasError
}

func (o *Deployments) GetBuildingAt() *int64 {
	if o == nil {
		return nil
	}
	return o.BuildingAt
}

func (o *Deployments) GetChecksConclusion() *GetDeploymentsChecksConclusion {
	if o == nil {
		return nil
	}
	return o.ChecksConclusion
}

func (o *Deployments) GetChecksState() *GetDeploymentsChecksState {
	if o == nil {
		return nil
	}
	return o.ChecksState
}

func (o *Deployments) GetConnectBuildsEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.ConnectBuildsEnabled
}

func (o *Deployments) GetConnectConfigurationID() *string {
	if o == nil {
		return nil
	}
	return o.ConnectConfigurationID
}

func (o *Deployments) GetCreated() int64 {
	if o == nil {
		return 0
	}
	return o.Created
}

func (o *Deployments) GetCreatedAt() *int64 {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *Deployments) GetCreator() GetDeploymentsCreator {
	if o == nil {
		return GetDeploymentsCreator{}
	}
	return o.Creator
}

func (o *Deployments) GetInspectorURL() *string {
	if o == nil {
		return nil
	}
	return o.InspectorURL
}

func (o *Deployments) GetIsRollbackCandidate() *bool {
	if o == nil {
		return nil
	}
	return o.IsRollbackCandidate
}

func (o *Deployments) GetMeta() map[string]string {
	if o == nil {
		return nil
	}
	return o.Meta
}

func (o *Deployments) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Deployments) GetProjectSettings() *GetDeploymentsProjectSettings {
	if o == nil {
		return nil
	}
	return o.ProjectSettings
}

func (o *Deployments) GetReady() *int64 {
	if o == nil {
		return nil
	}
	return o.Ready
}

func (o *Deployments) GetReadySubstate() *GetDeploymentsReadySubstate {
	if o == nil {
		return nil
	}
	return o.ReadySubstate
}

func (o *Deployments) GetSource() *GetDeploymentsSource {
	if o == nil {
		return nil
	}
	return o.Source
}

func (o *Deployments) GetState() *State {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *Deployments) GetTarget() *GetDeploymentsTarget {
	if o == nil {
		return nil
	}
	return o.Target
}

func (o *Deployments) GetType() GetDeploymentsType {
	if o == nil {
		return GetDeploymentsType("")
	}
	return o.Type
}

func (o *Deployments) GetUID() string {
	if o == nil {
		return ""
	}
	return o.UID
}

func (o *Deployments) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

type GetDeploymentsResponseBody struct {
	Deployments []Deployments `json:"deployments"`
	// This object contains information related to the pagination of the current request, including the necessary parameters to get the next or previous page of data.
	Pagination shared.Pagination `json:"pagination"`
}

func (o *GetDeploymentsResponseBody) GetDeployments() []Deployments {
	if o == nil {
		return []Deployments{}
	}
	return o.Deployments
}

func (o *GetDeploymentsResponseBody) GetPagination() shared.Pagination {
	if o == nil {
		return shared.Pagination{}
	}
	return o.Pagination
}

type GetDeploymentsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	Object      *GetDeploymentsResponseBody
}

func (o *GetDeploymentsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetDeploymentsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetDeploymentsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetDeploymentsResponse) GetObject() *GetDeploymentsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
