// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"vercel/internal/sdk/pkg/models/shared"
)

type GetEdgeConfigTokensSecurity struct {
	BearerToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type GetEdgeConfigTokensRequest struct {
	EdgeConfigID string `pathParam:"style=simple,explode=false,name=edgeConfigId"`
	// The Team identifier or slug to perform the request on behalf of.
	TeamID *string `queryParam:"style=form,explode=true,name=teamId"`
}

type GetEdgeConfigTokensResponse struct {
	ContentType string
	// The EdgeConfig.
	EdgeConfigToken *shared.EdgeConfigToken
	StatusCode      int
	RawResponse     *http.Response
}
